{
  "openapi": "3.0.0",
  "info": {
    "title": "rest-api-slim-php-sql",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://rest-api-slim-php-sql.herokuapp.com",
      "variables": {}
    }
  ],
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Info"
        ],
        "summary": "Get Help",
        "operationId": "GetHelp",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/status": {
      "get": {
        "tags": [
          "Info"
        ],
        "summary": "Get Status",
        "operationId": "GetStatus",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Info"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "example": {
                "email": "fercalmet@gmail.com",
                "password": "AnyPass1000"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/signup": {
      "post": {
        "tags": [
          "Info"
        ],
        "summary": "SignUp",
        "operationId": "SignUp",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignUpRequest"
              },
              "example": {
                "email": "fercalmet@gmail.com",
                "password": "AnyPass1000",
                "first_name": "Fernando",
                "last_name": "Calmet",
                "gender": "Male",
                "birthday": "1989-01-01"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/api/v1/profiles": {
      "post": {
        "tags": [
          "Profiles"
        ],
        "summary": "Create",
        "operationId": "Create",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest"
              },
              "example": {
                "username": "Fernando Calmet",
                "biography": "Hello World!"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Profiles"
        ],
        "summary": "GetAll",
        "operationId": "GetAll",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/profiles/1": {
      "get": {
        "tags": [
          "Profiles"
        ],
        "summary": "GetOne",
        "operationId": "GetOne",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Profiles"
        ],
        "summary": "Update",
        "operationId": "Update",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest"
              },
              "example": {
                "username": "Fernando Calmet",
                "biography": "Hello World!"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/users/1": {
      "delete": {
        "tags": [
          "Profiles"
        ],
        "summary": "Delete",
        "operationId": "Delete",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "GetOne",
        "operationId": "GetOne12345",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update",
        "operationId": "PutUpdate1234",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest5"
              },
              "example": {
                "email": "khanakat@gmail.com",
                "password": "AnyPass1000",
                "first_name": "Fernando",
                "last_name": "Calmet",
                "gender": "Male"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/profiles/search/software": {
      "get": {
        "tags": [
          "Profiles"
        ],
        "summary": "Search",
        "operationId": "Search",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/roles": {
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Create",
        "operationId": "PostCreate",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest1"
              },
              "example": {
                "name": "Support",
                "description": "Desktop Helper"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "GetAll",
        "operationId": "GetAll1",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/roles/1": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "GetOne",
        "operationId": "GetOne1",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Roles"
        ],
        "summary": "Update",
        "operationId": "PutUpdate",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest1"
              },
              "example": {
                "name": "Supervisor",
                "description": "View all features."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Delete",
        "operationId": "Delete1",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/roles/search/Admin": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Search",
        "operationId": "GetSearch",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/modules": {
      "post": {
        "tags": [
          "Modules"
        ],
        "summary": "Create",
        "operationId": "PostCreate1",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest1"
              },
              "example": {
                "name": "This a sample",
                "description": "My own example from postman."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Modules"
        ],
        "summary": "GetAll",
        "operationId": "GetAll12",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/modules/1": {
      "get": {
        "tags": [
          "Modules"
        ],
        "summary": "GetOne",
        "operationId": "GetOne12",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Modules"
        ],
        "summary": "Update",
        "operationId": "PutUpdate1",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest1"
              },
              "example": {
                "name": "This a second sample",
                "description": "My own example from postman."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "delete": {
        "tags": [
          "Modules"
        ],
        "summary": "Delete",
        "operationId": "Delete12",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/modules/search/profiles": {
      "get": {
        "tags": [
          "Modules"
        ],
        "summary": "Search",
        "operationId": "GetSearch1",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/permissions": {
      "post": {
        "tags": [
          "Permissions"
        ],
        "summary": "Create",
        "operationId": "PostCreate12",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest3"
              },
              "example": {
                "role_id": 1,
                "operation_id": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Permissions"
        ],
        "summary": "GetAll",
        "operationId": "GetAll123",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/permissions/1": {
      "get": {
        "tags": [
          "Permissions"
        ],
        "summary": "GetOne",
        "operationId": "GetOne123",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Permissions"
        ],
        "summary": "Update",
        "operationId": "PutUpdate12",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest3"
              },
              "example": {
                "role_id": 2,
                "operation_id": 2
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "delete": {
        "tags": [
          "Permissions"
        ],
        "summary": "Delete",
        "operationId": "Delete123",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/permissions/search/1": {
      "get": {
        "tags": [
          "Permissions"
        ],
        "summary": "Search",
        "operationId": "GetSearch12",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/operations": {
      "post": {
        "tags": [
          "Operations"
        ],
        "summary": "Create",
        "operationId": "PostCreate123",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest1"
              },
              "example": {
                "name": "Postman Test Operation",
                "description": "This is just a test."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Operations"
        ],
        "summary": "GetAll",
        "operationId": "GetAll1234",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/operations/1": {
      "get": {
        "tags": [
          "Operations"
        ],
        "summary": "GetOne",
        "operationId": "GetOne1234",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "put": {
        "tags": [
          "Operations"
        ],
        "summary": "Update",
        "operationId": "PutUpdate123",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRequest1"
              },
              "example": {
                "name": "Postman Testing Operation",
                "description": "Hello World."
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "delete": {
        "tags": [
          "Operations"
        ],
        "summary": "Delete",
        "operationId": "Delete1234",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/operations/search/create": {
      "get": {
        "tags": [
          "Operations"
        ],
        "summary": "Search",
        "operationId": "GetSearch123",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create",
        "operationId": "PostCreate1234",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRequest5"
              },
              "example": {
                "email": "fercalmet@gmail.com",
                "password": "AnyPass1000",
                "first_name": "Fernando",
                "last_name": "Calmet",
                "gender": "Male",
                "birthday": "1989-06-09"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "GetAll",
        "operationId": "GetAll12345",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "application/json"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/v1/users/search/fernando": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Search",
        "operationId": "GetSearch1234",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{jwt}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false,
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "fercalmet@gmail.com",
          "password": "AnyPass1000"
        }
      },
      "SignUpRequest": {
        "title": "SignUpRequest",
        "required": [
          "email",
          "password",
          "first_name",
          "last_name",
          "gender",
          "birthday"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "birthday": {
            "type": "string"
          }
        },
        "example": {
          "email": "fercalmet@gmail.com",
          "password": "AnyPass1000",
          "first_name": "Fernando",
          "last_name": "Calmet",
          "gender": "Male",
          "birthday": "1989-01-01"
        }
      },
      "CreateRequest": {
        "title": "CreateRequest",
        "required": [
          "username",
          "biography"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "biography": {
            "type": "string"
          }
        },
        "example": {
          "username": "Fernando Calmet",
          "biography": "Hello World!"
        }
      },
      "UpdateRequest": {
        "title": "UpdateRequest",
        "required": [
          "username",
          "biography"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "biography": {
            "type": "string"
          }
        },
        "example": {
          "username": "Fernando Calmet",
          "biography": "Hello World!"
        }
      },
      "CreateRequest1": {
        "title": "CreateRequest1",
        "required": [
          "name",
          "description"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "example": {
          "name": "Support",
          "description": "Desktop Helper"
        }
      },
      "UpdateRequest1": {
        "title": "UpdateRequest1",
        "required": [
          "name",
          "description"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "example": {
          "name": "Supervisor",
          "description": "View all features."
        }
      },
      "CreateRequest3": {
        "title": "CreateRequest3",
        "required": [
          "role_id",
          "operation_id"
        ],
        "type": "object",
        "properties": {
          "role_id": {
            "type": "integer",
            "format": "int32"
          },
          "operation_id": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "role_id": 1,
          "operation_id": 1
        }
      },
      "UpdateRequest3": {
        "title": "UpdateRequest3",
        "required": [
          "role_id",
          "operation_id"
        ],
        "type": "object",
        "properties": {
          "role_id": {
            "type": "integer",
            "format": "int32"
          },
          "operation_id": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "role_id": 2,
          "operation_id": 2
        }
      },
      "CreateRequest5": {
        "title": "CreateRequest5",
        "required": [
          "email",
          "password",
          "first_name",
          "last_name",
          "gender",
          "birthday"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "birthday": {
            "type": "string"
          }
        },
        "example": {
          "email": "fercalmet@gmail.com",
          "password": "AnyPass1000",
          "first_name": "Fernando",
          "last_name": "Calmet",
          "gender": "Male",
          "birthday": "1989-06-09"
        }
      },
      "UpdateRequest5": {
        "title": "UpdateRequest5",
        "required": [
          "email",
          "password",
          "first_name",
          "last_name",
          "gender"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "first_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          }
        },
        "example": {
          "email": "khanakat@gmail.com",
          "password": "AnyPass1000",
          "first_name": "Fernando",
          "last_name": "Calmet",
          "gender": "Male"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Info"
    },
    {
      "name": "Profiles"
    },
    {
      "name": "Roles"
    },
    {
      "name": "Modules"
    },
    {
      "name": "Permissions"
    },
    {
      "name": "Operations"
    },
    {
      "name": "Users"
    }
  ]
}